pb_phone_book_homepage:
    path:     /
    defaults: { _controller: PBPhoneBookBundle:Default:main }

pb_phone_book_index:
    path:     /phonebook
    defaults: { _controller: PBPhoneBookBundle:Default:index }