pb_phone_book_homepage:
    path:     /
    defaults: { _controller: PBPhoneBookBundle:Default:main }

pb_phone_book_index:
    path:     /phonebook
    defaults: { _controller: PBPhoneBookBundle:Default:index }

pb_phone_book_create:
    path:     /create
    defaults: { _controller: PBPhoneBookBundle:Default:create }

pb_phone_book_show:
    path:     /show/{id}
    defaults: { _controller: PBPhoneBookBundle:Default:show }