<?php

namespace PB\PhoneBookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneBookRepository extends EntityRepository
{
    public function findAllOrderedById()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT pb FROM PBPhoneBookBundle:PhoneBook pb ORDER BY pb.id ASC')
            ->getResult();
    }
}
